name: Night evaluate

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  eval-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run evaluator
        run: |
          python -m src.evaluate

      - name: Upload artifact for pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
